cloud:
  aws:
    credentials:
      accessKey: AKIA253Y5KG62RJGYHGR
      secretKey: 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
    region:
      static: us-east-1
    s3:
      bucket:
        name: dailyduploads